#ifndef BURROWSWHEELER_TRANSFORM_CONSTANTS_H
#define BURROWSWHEELER_TRANSFORM_CONSTANTS_H

constexpr char END_SYMBOL = '$';
constexpr size_t MAX_LENGTH = 100;

#endif //BURROWSWHEELER_TRANSFORM_CONSTANTS_H
